backbone:
  config: mit_b1
  stride: [4, 2, 2, 1]
  comments: None

scheme: transwcd_dual # transwcd_single, transwcd_dual

dataset:
  root_dir: /data/zhenghui.zhao/Dataset/Change Detection/DSIFN-CD-256
  name_list_dir: datasets/DSIFN
  num_classes: 2
  crop_size: 256
  rescale_range: [0.5, 2.0]

work_dir:
  dir: work_dir_DSIFN
  ckpt_dir: checkpoints
  pred_dir: predictions
  logger_dir: logger

train:
  split: train
  batch_size: 32
  max_iters: 40000
  cam_iters: 2000
  eval_iters: 500
  log_iters: 500

cam:
  bkg_score: 0.45
  scales: [1, 0.5, 1.5, 2.0]

val:
  split: val
  bacth_size: 1

test:
  split: test
  batch_size: 1


optimizer:
  type: AdamW
  learning_rate: 6e-5
  betas: [0.9, 0.999]
  weight_decay: 0.01

scheduler:
  warmup_iter: 1500
  warmup_ratio: 1e-6
  power: 1.0
